ci: add test workflow
PerimeterX/flast pull request #2
Opened 2022-07-09 10:37 UTC by naorpeled

2022-07-09 10:53 UTC, naorpeled commented
For some reason the tests are failing in Node 10 and 12,
not sure why but unfortunately won't be able to investigate further today.

2022-07-10 12:51 UTC, BenBaryoPX commented
I believe the earliest node version supported is 14

2022-07-10 12:52 UTC, BenBaryoPX commented
I've added some tests yesterday following another PR. Could you run the flow and see that everything works?

2022-07-10 13:11 UTC, naorpeled commented
> I've added some tests yesterday following another PR. Could you run the flow and see that everything works?

Sure!

2022-07-10 16:01 UTC, naorpeled commented
> I've added some tests yesterday following another PR. Could you run the flow and see that everything works?

The workflow is passing

2022-07-11 06:09 UTC, BenBaryoPX requested changes

2022-07-11 06:40 UTC, naorpeled commented on package.json
> +    "lint": "eslint .",
It's a dev dependency, therefore it would be available within npm install/ci context, so it's redundant.

2022-07-11 07:52 UTC, BenBaryoPX approved these changes

2022-07-11 07:52 UTC, merged